# Generated by Django 6.0.4 on 2026-04-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_done_alter_project_name_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
