# Generated by Django 6.0.4 on 2026-04-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
